### ISSUE TITLE
As a user, i want to mark when i had that feeling

### ISSUE THREAD

**Issue by hzuppur** [hzuppur/FEEL#17]
Time estimation : 1h

**Comment by siimanderson** [comment]
![Kuvatõmmis (176)](https://user-images.githubusercontent.com/44437574/98792151-bd5c0a80-240e-11eb-968c-12050e136f8e.png)
![Kuvatõmmis (177)](https://user-images.githubusercontent.com/44437574/98792156-be8d3780-240e-11eb-8e2d-1aa31d3d53d4.png)
![Kuvatõmmis (178)](https://user-images.githubusercontent.com/44437574/98792157-be8d3780-240e-11eb-96d7-62f22c5f9314.png)
