### ISSUE TITLE
As a user, i want to write down how i reacted

### ISSUE THREAD

**Issue by hzuppur** [hzuppur/FEEL#18]
Time estimation : 2h

**Comment by siimanderson** [comment]
![Kuvatõmmis (174)](https://user-images.githubusercontent.com/44437574/98791897-5f2f2780-240e-11eb-9ba5-d7ea39fdffc5.png)
![Kuvatõmmis (175)](https://user-images.githubusercontent.com/44437574/98791900-60605480-240e-11eb-8eee-177a4c40291d.png)
