### ISSUE TITLE
As an end user, I want to be able to write down what triggered my emotions.

### ISSUE THREAD

**Issue by hzuppur** [hzuppur/FEEL#2]
Time estimation: 2h

**Comment by siimanderson** [comment]
![Kuvatõmmis (169)](https://user-images.githubusercontent.com/44437574/98791522-d912e100-240d-11eb-9f9a-5271e2493b64.png)
![Kuvatõmmis (170)](https://user-images.githubusercontent.com/44437574/98791526-d9ab7780-240d-11eb-81b3-2e32693be553.png)
