### ISSUE TITLE
As a patient I want to scale the intensity of my feelings.

### ISSUE THREAD

**Issue by hzuppur** [hzuppur/FEEL#4]
Time estimation : 2h

**Comment by siimanderson** [comment]
![Kuvatõmmis (164)](https://user-images.githubusercontent.com/44437574/98790510-84229b00-240c-11eb-91bf-6ec4f41f270b.png)
![Kuvatõmmis (165)](https://user-images.githubusercontent.com/44437574/98790514-8553c800-240c-11eb-8cd8-e5b4b35f0098.png)
![Kuvatõmmis (166)](https://user-images.githubusercontent.com/44437574/98790516-85ec5e80-240c-11eb-81cd-81a8d71b3127.png)

**Comment by siimanderson** [comment]
![Kuvatõmmis (167)](https://user-images.githubusercontent.com/44437574/98791062-2e022780-240d-11eb-907c-96c83a51af7f.png)
