### ISSUE TITLE
As a patient, I want to have the option of either getting to know my emotion better or to just feel better.

### ISSUE THREAD

**Issue by hzuppur** [hzuppur/FEEL#6]
Time estimation : 1h

**Comment by siimanderson** [comment]
![Uploading Kuvatõmmis (179).png…]()

**Comment by siimanderson** [comment]
![Kuvatõmmis (179)](https://user-images.githubusercontent.com/44437574/98792314-f98f6b00-240e-11eb-8021-a1e63c42ccb3.png)
